DROP DATABASE IF EXISTS UTS;
CREATE DATABASE UTS;
USE UTS;

DELIMITER ##
CREATE PROCEDURE spNomor3(pKalimat varchar(255))
BEGIN
DECLARE input varchar(40);
DECLARE KETERANGAN VARCHAR(1000);
DECLARE A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z INT;
DECLARE COUNTER INT;
DECLARE PANJANG INT;
DECLARE HURUF VARCHAR(1);
SET KETERANGAN ="";
SET HURUF="";
SET COUNTER = 1;
SET PANJANG = LENGTH(input);
SET input = pkalimat;
SET A=0;
SET B=0;
SET C=0;
SET D=0;
SET E=0;
SET F=0;
SET G=0;
SET H=0;
SET I=0;
SET J=0;
SET K=0;
SET L=0;
SET M=0;
SET N=0;
SET O=0;
SET P=0;
SET Q=0;
SET R=0;
SET S=0;
SET T=0;
SET U=0;
SET V=0;
SET W=0;
SET X=0;
SET Y=0;
SET Z=0;

WHILE COUNTER <= PANJANG DO
SET HURUF=SUBSTRING(input,COUNTER,1);
CASE
WHEN HURUF = 'A' OR HURUF = 'a' THEN SET A=A+1;
WHEN HURUF = 'B' OR HURUF = 'b' THEN SET B=B+1;
WHEN HURUF = 'C' OR HURUF = 'c' THEN SET C=C+1;
WHEN HURUF = 'D' OR HURUF = 'd' THEN SET D=D+1;
WHEN HURUF = 'E' OR HURUF = 'e' THEN SET E=E+1;
WHEN HURUF = 'F' OR HURUF = 'f' THEN SET F=F+1;
WHEN HURUF = 'G' OR HURUF = 'g' THEN SET G=G+1;
WHEN HURUF = 'H' OR HURUF = 'h' THEN SET H=H+1;
WHEN HURUF = 'I' OR HURUF = 'i' THEN SET I=I+1;
WHEN HURUF = 'J' OR HURUF = 'j' THEN SET J=J+1;
WHEN HURUF = 'K' OR HURUF = 'k' THEN SET K=K+1;
WHEN HURUF = 'L' OR HURUF = 'l' THEN SET L=L+1;
WHEN HURUF = 'M' OR HURUF = 'm' THEN SET M=M+1;
WHEN HURUF = 'N' OR HURUF = 'n' THEN SET N=N+1;
WHEN HURUF = 'O' OR HURUF = 'o' THEN SET O=O+1;
WHEN HURUF = 'P' OR HURUF = 'p' THEN SET P=P+1;
WHEN HURUF = 'Q' OR HURUF = 'q' THEN SET Q=Q+1;
WHEN HURUF = 'R' OR HURUF = 'r' THEN SET R=R+1;
WHEN HURUF = 'S' OR HURUF = 's' THEN SET S=S+1;
WHEN HURUF = 'T' OR HURUF = 't' THEN SET T=T+1;
WHEN HURUF = 'U' OR HURUF = 'u' THEN SET U=U+1;
WHEN HURUF = 'V' OR HURUF = 'v' THEN SET V=V+1;
WHEN HURUF = 'W' OR HURUF = 'w' THEN SET W=W+1;
WHEN HURUF = 'X' OR HURUF = 'x' THEN SET X=X+1;
WHEN HURUF = 'Y' OR HURUF = 'y' THEN SET Y=Y+1;
WHEN HURUF = 'A' OR HURUF = 'z' THEN SET Z=Z+1;
END CASE;
set COUNTER = COUNTER+1;
END WHILE;

SET COUNTER =1;
WHILE COUNTER <= PANJANG DO
CASE
WHEN A > 0 THEN SET KETERANGAN = CONCAT('HURUF A ADA : ', A);
WHEN B > 0 THEN SET KETERANGAN = CONCAT('HURUF B ADA : ', B);
WHEN C > 0 THEN SET KETERANGAN = CONCAT('HURUF C ADA : ', C);
WHEN D > 0 THEN SET KETERANGAN = CONCAT('HURUF D ADA : ', D);
WHEN E > 0 THEN SET KETERANGAN = CONCAT('HURUF E ADA : ', E);
WHEN F > 0 THEN SET KETERANGAN = CONCAT('HURUF F ADA : ', F);
WHEN G > 0 THEN SET KETERANGAN = CONCAT('HURUF G ADA : ', G);
WHEN H > 0 THEN SET KETERANGAN = CONCAT('HURUF H ADA : ', H);
WHEN I > 0 THEN SET KETERANGAN = CONCAT('HURUF I ADA : ', I);
WHEN J > 0 THEN SET KETERANGAN = CONCAT('HURUF J ADA : ', J);
WHEN K > 0 THEN SET KETERANGAN = CONCAT('HURUF K ADA : ', K);
WHEN L > 0 THEN SET KETERANGAN = CONCAT('HURUF L ADA : ', L);
WHEN M > 0 THEN SET KETERANGAN = CONCAT('HURUF M ADA : ', M);
WHEN N > 0 THEN SET KETERANGAN = CONCAT('HURUF N ADA : ', N);
WHEN O > 0 THEN SET KETERANGAN = CONCAT('HURUF O ADA : ', O);
WHEN P > 0 THEN SET KETERANGAN = CONCAT('HURUF P ADA : ', P);
WHEN Q > 0 THEN SET KETERANGAN = CONCAT('HURUF Q ADA : ', Q);
WHEN R > 0 THEN SET KETERANGAN = CONCAT('HURUF R ADA : ', R);
WHEN S > 0 THEN SET KETERANGAN = CONCAT('HURUF S ADA : ', S);
WHEN T > 0 THEN SET KETERANGAN = CONCAT('HURUF T ADA : ', T);
WHEN U > 0 THEN SET KETERANGAN = CONCAT('HURUF U ADA : ', U);
WHEN V > 0 THEN SET KETERANGAN = CONCAT('HURUF V ADA : ', V);
WHEN W > 0 THEN SET KETERANGAN = CONCAT('HURUF W ADA : ', W);
WHEN X > 0 THEN SET KETERANGAN = CONCAT('HURUF X ADA : ', X);
WHEN Y > 0 THEN SET KETERANGAN = CONCAT('HURUF Y ADA : ', Y);
WHEN A > 0 THEN SET KETERANGAN = CONCAT('HURUF Z ADA : ', Z);
END CASE;
CASE
WHEN A > 0 THEN SET A = 0;
WHEN B > 0 THEN SET B = 0;
WHEN C > 0 THEN SET C = 0;
WHEN D > 0 THEN SET D = 0;
WHEN E > 0 THEN SET E = 0;
WHEN F > 0 THEN SET F = 0;
WHEN G > 0 THEN SET G = 0;
WHEN H > 0 THEN SET H = 0;
WHEN I > 0 THEN SET I = 0;
WHEN J > 0 THEN SET J = 0;
WHEN K > 0 THEN SET K = 0;
WHEN L > 0 THEN SET L = 0;
WHEN M > 0 THEN SET M = 0;
WHEN N > 0 THEN SET N = 0;
WHEN O > 0 THEN SET O = 0;
WHEN P > 0 THEN SET P = 0;
WHEN Q > 0 THEN SET Q = 0;
WHEN R > 0 THEN SET R = 0;
WHEN S > 0 THEN SET S = 0;
WHEN T > 0 THEN SET T = 0;
WHEN U > 0 THEN SET U = 0;
WHEN V > 0 THEN SET V = 0;
WHEN W > 0 THEN SET W = 0;
WHEN X > 0 THEN SET X = 0;
WHEN Y > 0 THEN SET Y = 0;
WHEN A > 0 THEN SET Z = 0;
END CASE;
SET COUNTER = COUNTER+1;
END WHILE;

SELECT input AS 'INPUTAN',
keterangan AS 'HURUF';

END;
##
DELIMITER ;

CALL spNomor3('ular berlari lurus');
